server:
  port:
    8201
spring:
  application:
    name: jka-feign
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true