server:
  port: 8888

spring:
  application:
    name: JkaConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lxbyes/config-repo.git
          deleteUntrackedBranches: true
          #refreshRate: 0