---
kind: Service
apiVersion: v1
metadata:
  name: configclient
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    targetPort: 8001
    port: 8001
    nodePort: 32101
  selector:
    app: configclient

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configclient
  labels:
    app: configclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configclient
  template:
    metadata:
      labels:
        app: configclient
    spec:
      containers:
      - name: configclient
        image: 10.28.100.57:5000/jka-configclient:latest
        ports:
        - containerPort: 8001
        command: ["java"]
        args: ["-Dserver.port=8001", "-Djava.security.egd=file:/dev/./urandom","-server","-Xmx1g","-Xms1g","-XX:+DisableExplicitGC","-XX:+UseConcMarkSweepGC",
        "-XX:+CMSParallelRemarkEnabled","-XX:LargePageSizeInBytes=128m","-XX:+UseFastAccessorMethods","-XX:+UseCMSInitiatingOccupancyOnly",
        "-XX:CMSInitiatingOccupancyFraction=70","-Xloggc:/logs/gc.log","-verbose:gc","-XX:+PrintGCDetails","-XX:+HeapDumpOnOutOfMemoryError",
        "-XX:HeapDumpPath=/logs/","-Duser.timezone=GMT+08","-jar","/app/jka-configclient.jar"]