### application=foo profile=development
GET http://localhost:8888/foo/development

### application=foo profile=myprofile label=test
GET http://localhost:8888/foo/myprofile/test

###
GET http://localhost:8888/jka-client/default

###
POST http://localhost:8888/actuator/bus-refresh

###