server:
  port: 8761

spring:
  application:
    name: jka-eureakserver

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

