server:
  port: 8201
spring:
  application:
    name: jka-bytetccprovider
  datasource:
    name: provider
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/bytetcc_provider?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
org:
  bytesoft:
    bytetcc:
      datasource:
        autoconfig: false